"""Data from meteo stations for various cities,
which Polimarket relies on, to confirm weather forecasts."""

TEMPERATURE_STATIONS = {
	"Amsterdam": {
		"station_name": "Amsterdam Airport Schiphol Station",
		"station_lat": 52.299459,
		"station_lon": 4.795316,
		"link": "https://www.wunderground.com/history/daily/nl/schiphol/EHAM",
	},
	"Ankara": {
		"station_name": "Esenboğa Intl Airport Station",
		"station_lat": 40.117432,
		"station_lon": 33.009840,
		"link": "https://www.wunderground.com/history/daily/tr/%C3%A7ubuk/LTAC",
	},
	"Atlanta": {
		"station_name": "Hartsfield-Jackson International Airport Station",
		"station_lat": 33.633107,
		"station_lon": -84.411074,
		"link": "https://www.wunderground.com/history/daily/us/ga/atlanta/KATL",
	},
	"Austin": {
		"station_name": "Austin-Bergstrom International Airport Station",
		"station_lat": 30.185373,
		"station_lon": -97.656822,
		"link": "https://www.wunderground.com/history/daily/us/tx/austin/KAUS",
	},
	"Beijing": {
		"station_name": "Beijing Capital International Airport Station",
		"station_lat": 40.072249,
		"station_lon": 116.587934,
		"link": "https://www.wunderground.com/history/daily/cn/beijing/ZBAA",
	},
	"Buenos Aires": {
		"station_name": "Minister Pistarini Intl Airport Station",
		"station_lat": -34.815599,
		"station_lon": -58.526049,
		"link": "https://www.wunderground.com/history/daily/ar/ezeiza/SAEZ",
	},
	"Busan": {
		"station_name": "Gimhae Intl Airport Station",
		"station_lat": 35.177792,
		"station_lon": 128.934799,
		"link": "https://www.wunderground.com/history/daily/kr/busan/RKPK",
	},
	"Cape Town": {
		"station_name": "Cape Town International Airport Station",
		"station_lat": -33.963019,
		"station_lon": 18.608226,
		"link": "https://www.wunderground.com/history/daily/za/matroosfontein/FACT",
	},
	"Chengdu": {
		"station_name": "Chengdu Shuangliu International Airport Station",
		"station_lat": 30.570000,
		"station_lon": 103.960000,
		"link": "https://www.wunderground.com/history/daily/cn/chengdu/ZUUU",
	},
	"Chicago": {
		"station_name": "Chicago O'Hare Intl Airport Station",
		"station_lat": 41.984253,
		"station_lon": -87.939897,
		"link": "https://www.wunderground.com/history/daily/us/il/chicago/KORD",
	},
	"Chongqing": {
		"station_name": "Chongqing Jiangbei International Airport Station",
		"station_lat": 29.735954,
		"station_lon": 106.647301,
		"link": "https://www.wunderground.com/history/daily/cn/chongqing/ZUCK",
	},
	"Dallas": {
		"station_name": "Dallas Love Field Station",
		"station_lat": 32.829000,
		"station_lon": -96.878000,
		"link": "https://www.wunderground.com/history/daily/us/tx/dallas/KDAL",
	},
	"Denver": {
		"station_name": "Buckley Space Force Base Station",
		"station_lat": 39.710690,
		"station_lon": -104.758343,
		"link": "https://www.wunderground.com/history/daily/us/co/aurora/KBKF",
	},
	"Helsinki": {
		"station_name": "Helsinki Vantaa Airport Station",
		"station_lat": 60.321489,
		"station_lon": 24.979285,
		"link": "https://www.wunderground.com/history/daily/fi/vantaa/EFHK",
	},
	"Hong Kong": {
		"station_name": "Hong Kong Observatory",
		"station_lat": 22.302242,
		"station_lon": 114.174377,
		"link": "https://www.weather.gov.hk/en/cis/climat.htm",
	},
	"Houston": {
		"station_name": "William P. Hobby Airport Station",
		"station_lat": 29.644760,
		"station_lon": -95.264350,
		"link": "https://www.wunderground.com/history/daily/us/tx/houston/KHOU",
	},
	"Jakarta": {
		"station_name": "Halim Perdanakusuma Intl Airport Station",
		"station_lat": -6.269065,
		"station_lon": 106.885187,
		"link": "https://www.wunderground.com/history/daily/id/jakarta/WIHH",
	},
	"Jeddah": {
		"station_name": "King Abdulaziz International Airport Station",
		"station_lat": 21.669721,
		"station_lon": 39.153228,
		"link": "https://www.wunderground.com/history/daily/sa/jeddah/OEJN",
	},
	"Istanbul": {
		"station_name": "Istanbul Airport",
		"station_lat": 41.262948,
		"station_lon": 28.74133,
		"link": "https://www.weather.gov/wrh/timeseries?site=LTFM",
	},
	"Karachi": {
		"station_name": "Masroor Airbase Station",
		"station_lat": 24.891759,
		"station_lon": 66.944076,
		"link": "https://www.wunderground.com/history/daily/pk/karachi/OPKC",
	},
	"Kuala Lumpur": {
		"station_name": "Kuala Lumpur Intl Airport Station",
		"station_lat": 2.714494,
		"station_lon": 101.706833,
		"link": "https://www.wunderground.com/history/daily/my/sepang-district/WMKK",
	},
	"Lagos": {
		"station_name": "Murtala Muhammad International Airport Station",
		"station_lat": 6.572059,
		"station_lon": 3.307076,
		"link": "https://www.wunderground.com/history/daily/ng/lagos/DNMM",
	},
	"London": {
		"station_name": "London City Airport",
		"station_lat": 51.514000,
		"station_lon": 0.037000,
		"link": "https://www.wunderground.com/history/daily/gb/london/EGLC",
	},
	"Los Angeles": {
		"station_name": "Los Angeles International Airport Station",
		"station_lat": 33.933419,
		"station_lon": -118.396211,
		"link": "https://www.wunderground.com/history/daily/us/ca/los-angeles/KLAX",
	},
	"Lucknow": {
		"station_name": "Chaudhary Charan Singh Intl Airport Station",
		"station_lat": 26.758819,
		"station_lon": 80.887674,
		"link": "https://www.wunderground.com/history/daily/in/lucknow/VILK",
	},
	"Madrid": {
		"station_name": "Adolfo Suárez Madrid-Barajas Airport Station",
		"station_lat": 40.476491,
		"station_lon": -3.577349,
		"link": "https://www.wunderground.com/history/daily/es/madrid/LEMD",
	},
	"Manila": {
		"station_name": "Ninoy Aquino International Airport Station",
		"station_lat": 14.516976,
		"station_lon": 121.007843,
		"link": "https://www.wunderground.com/history/daily/ph/manila/RPLL",
	},
	"Mexico City": {
		"station_name": "Benito Juárez International Airport Station",
		"station_lat": 19.441427,
		"station_lon": -99.074672,
		"link": "https://www.wunderground.com/history/daily/mx/mexico-city/MMMX",
	},
	"Miami": {
		"station_name": "Miami Intl Airport Station",
		"station_lat": 25.807654,
		"station_lon": -80.289509,
		"link": "https://www.wunderground.com/history/daily/us/fl/miami/KMIA",
	},
	"Milan": {
		"station_name": "Malpensa Intl Airport Station",
		"station_lat": 45.622311,
		"station_lon": 8.724912,
		"link": "https://www.wunderground.com/history/daily/it/milan/LIMC",
	},
	"Moscow": {
		"station_name": "Vnukovo International Airport",
		"station_lat": 55.589216,
		"station_lon": 37.269568,
		"link": "https://www.weather.gov/wrh/timeseries?site=UUWW",
	},
	"Munich": {
		"station_name": "Munich Airport Station",
		"station_lat": 48.343300,
		"station_lon": 11.784796,
		"link": "https://www.wunderground.com/history/daily/de/munich/EDDM",
	},
	"NYC": {
		"station_name": "LaGuardia Airport Station",
		"station_lat": 40.777616,
		"station_lon": -73.872098,
		"link": "https://www.wunderground.com/history/daily/us/ny/new-york-city/KLGA",
	},
	"Panama City": {
		"station_name": "Marcos A. Gelabert Intl Airport Station",
		"station_lat": 8.980000,
		"station_lon": -79.560000,
		"link": "https://www.wunderground.com/history/daily/pa/panama-city/MPMG",
	},
	"Paris": {
		"station_name": "Paris-Le Bourget Airport Station",
		"station_lat": 48.959750,
		"station_lon": 2.428498,
		"link": "https://www.wunderground.com/history/daily/fr/bonneuil-en-france/LFPB",
	},
	"San Francisco": {
		"station_name": "San Francisco International Airport Station",
		"station_lat": 37.621338,
		"station_lon": -122.367811,
		"link": "https://www.wunderground.com/history/daily/us/ca/san-francisco/KSFO",
	},
	"Sao Paulo": {
		"station_name": "Sao Paulo-Guarulhos International Airport Station",
		"station_lat": -23.435735,
		"station_lon": -46.467602,
		"link": "https://www.wunderground.com/history/daily/br/guarulhos/SBGR",
	},
	"Seattle": {
		"station_name": "Seattle-Tacoma International Airport Station",
		"station_lat": 47.453492,
		"station_lon": -122.319874,
		"link": "https://www.wunderground.com/history/daily/us/wa/seatac/KSEA",
	},
	"Seoul": {
		"station_name": "Incheon Intl Airport Station",
		"station_lat": 37.481692,
		"station_lon": 126.522251,
		"link": "https://www.wunderground.com/history/daily/kr/incheon/RKSI",
	},
	"Shanghai": {
		"station_name": "Shanghai Pudong International Airport Station",
		"station_lat": 31.151553,
		"station_lon": 121.823534,
		"link": "https://www.wunderground.com/history/daily/cn/shanghai/ZSPD",
	},
	"Shenzhen": {
		"station_name": "Shenzhen Bao'an International Airport Station",
		"station_lat": 22.636886,
		"station_lon": 113.791517,
		"link": "https://www.wunderground.com/history/daily/cn/shenzhen/ZGSZ",
	},
	"Singapore": {
		"station_name": "Singapore Changi Airport Station",
		"station_lat": 1.362592,
		"station_lon": 103.979532,
		"link": "https://www.wunderground.com/history/daily/sg/singapore/WSSS",
	},
	"Taipei": {
		"station_name": "Taipei Songshan Airport Station",
		"station_lat": 25.071342,
		"station_lon": 121.553486,
		"link": "https://www.wunderground.com/history/daily/tw/taipei/RCSS",
	},
	"Tel Aviv": {
		"station_name": "Ben Gurion International Airport",
		"station_lat": 32.01140,
		"station_lon": 34.88670,
		"link": "https://www.weather.gov/wrh/timeseries?site=LLBG",
	},
	"Toronto": {
		"station_name": "Toronto Pearson Intl Airport Station",
		"station_lat": 43.665366,
		"station_lon": -79.603856,
		"link": "https://www.wunderground.com/history/daily/ca/mississauga/CYYZ",
	},
	"Warsaw": {
		"station_name": "Warsaw Chopin Airport Station",
		"station_lat": 52.160823,
		"station_lon": 20.987317,
		"link": "https://www.wunderground.com/history/daily/pl/warsaw/EPWA",
	},
	"Wellington": {
		"station_name": "Wellington Intl Airport Station",
		"station_lat": -41.324072,
		"station_lon": 174.805246,
		"link": "https://www.wunderground.com/history/daily/nz/wellington/NZWN",
	},
	"Wuhan": {
		"station_name": "Wuhan Tianhe International Airport Station",
		"station_lat": 30.784006,
		"station_lon": 114.204841,
		"link": "https://www.wunderground.com/history/daily/cn/wuhan/ZHHH",
	},
}
